INSERT INTO movies(title, genre, platform, rentalPrice, available, videoLink)
VALUES
('Shrek 2','Children','DVD', 1.99, 1, "xBgSfhp5Fxo"),
('Shrek 2','Children','DVD', 1.99, 1, "xBgSfhp5Fxo"),
('Shrek 2','Children','Blu-Ray', 2.99, 1, "xBgSfhp5Fxo"),
('Cars','Children','DVD', 1.99, 1, "WMQMuld6qPs"),
('Cars','Children','DVD', 1.99, 1, "WMQMuld6qPs"),
('Cars 2','Children','DVD', 1.99, 1, "lg5hj2c5Nkk"),
('Cars 3','Children','Blu-Ray', 2.99, 1, "2LeOH9AGJQM"),
('Toy Story','Children','DVD', 1.99, 1, "v-PjgYDrg70"),
('Toy Story','Children','DVD', 1.99, 1, "v-PjgYDrg70"),
('Toy Story 2','Children','DVD', 1.99, 1, "xNWSGRD5CzU"),
('Toy Story 2','Children','DVD', 1.99, 1, "xNWSGRD5CzU"),
('Detective Pikachu','Children','Blu-Ray', 2.99, 1, "1roy4o4tqQM"),
('Detective Pikachu','Children','Blu-Ray', 2.99, 1, "1roy4o4tqQM"),
('Detective Pikachu','Children','Blu-Ray', 2.99, 1, "1roy4o4tqQM"),

('Predator','Action','DVD', 1.99, 1, "_1wDBNHYDv8"),
('Predator','Action','DVD', 1.99, 1, "_1wDBNHYDv8"),
('Terminator 2: Judgment Day','Action','DVD', 1.99, 1, "CRRlbK5w8AE"),
('Terminator 2: Judgment Day','Action','DVD', 1.99, 1, "CRRlbK5w8AE"),
('Die Hard', 'Action', 'Blu-Ray', 2.99, 1, "jaJuwKCmJbY"),
('Die Hard', 'Action', 'Blu-Ray', 2.99, 1, "jaJuwKCmJbY"),
('Rocky III','Action','DVD', 1.99, 1, "gbRDCWKqvEc"),
('Rocky III','Action','DVD', 1.99, 1, "gbRDCWKqvEc"),
('Rocky III','Action','DVD', 1.99, 1, "gbRDCWKqvEc"),
('Harley Quinn: Birds of Prey','Action','Blu-Ray', 2.99, 1, "kGM4uYZzfu0"),
('Harley Quinn: Birds of Prey','Action','Blu-Ray', 2.99, 1, "kGM4uYZzfu0"),
('Harley Quinn: Birds of Prey','Action','Blu-Ray', 2.99, 1, "kGM4uYZzfu0"),
('Harley Quinn: Birds of Prey','Action','Blu-Ray', 2.99, 1, "kGM4uYZzfu0"),

('The Meg','Horror','DVD', 1.99, 1, "bsLk0NPRFAc"),
('The Meg','Horror','DVD', 1.99, 1, "bsLk0NPRFAc"),
('The Meg','Horror','Blu-Ray', 2.99, 1, "bsLk0NPRFAc"),
('A Quiet Place','Horror','DVD', 1.99, 1, "WR7cc5t7tv8"),
('A Quiet Place','Horror','DVD', 1.99, 1, "WR7cc5t7tv8"),
('A Quiet Place','Horror','Blu-Ray', 2.99, 1, "WR7cc5t7tv8"),
('Our House','Horror','DVD', 1.99, 1, "CkNB0w1fYKk"),
('Our House','Horror','DVD', 1.99, 1, "CkNB0w1fYKk"),
('Troll 2','Horror','Blu-Ray', 2.99, 1, "BhTgzfMwpiQ"),
('Troll 2','Horror','Blu-Ray', 2.99, 1, "BhTgzfMwpiQ"),
('Troll 2','Horror','Blu-Ray', 2.99, 1, "BhTgzfMwpiQ"),
('Troll 2','Horror','Blu-Ray', 2.99, 1, "BhTgzfMwpiQ"),
('Troll 2','Horror','Blu-Ray', 2.99, 1, "BhTgzfMwpiQ"),
('The Mangler','Horror','DVD', 1.99, 1, "BhTgzfMwpiQ"),

('Yesterday','Romance','DVD', 1.99, 1, "H3VeHyedL1U"),
('Yesterday','Romance','Blu-Ray', 2.99, 1, "H3VeHyedL1U"),
('Your Name','Romance','DVD', 1.99, 1, "o4-URMnBOPU"),
('Your Name','Romance','Blu-Ray', 2.99, 1, "o4-URMnBOPU"),
('Love, Simon','Romance','DVD', 1.99, 1, "E0cbWdlQg_8"),
('Love, Simon','Romance','Blu-Ray', 2.99, 1, "E0cbWdlQg_8"),
('I Still Believe','Romance','DVD', 1.99, 1, "YnxHyBbYwQQ"),
('I Still Believe','Romance','Blu-Ray', 2.99, 1, "YnxHyBbYwQQ"),
('The Fault in Our Stars','Romance','DVD', 1.99, 1, "9ItBvH5J6ss"),
('The Fault in Our Stars','Romance','Blu-Ray', 2.99, 1, "9ItBvH5J6ss"),

('The Last Airbender','Fantasy','DVD', 1.99, 1, "WdoiHMCVqMQ"),
('Twilight','Fantasy','DVD', 1.99, 1, "uxjNDE2fMjI"),
('Twilight','Fantasy','Blu-Ray', 2.99, 1, "uxjNDE2fMjI"),
('Clash of the Titans','Fantasy','DVD', 1.99, 1, "ojw1sau98Jg"),
('Clash of the Titans','Fantasy','Blu-Ray', 2.99, 1, "ojw1sau98Jg"),
('Percy Jackson and the Lightning Thief','Fantasy','DVD', 1.99, 1, "R86InkfdboA"),
('Percy Jackson and the Lightning Thief','Fantasy','Blu-Ray', 2.99, 1, "R86InkfdboA"),
('Prince of Persia','Fantasy','DVD', 1.99, 1, "bZ7Li5w2I-k"),
('Prince of Persia','Fantasy','Blu-Ray', 2.99, 1, "bZ7Li5w2I-k")